version: "3"

services:
  mongodb:
    image: "mongo"
  ports:
  - "27017:27017"
	backend:
		build:
			context: ./backend/
			dockerfile: ./Dockerfile
		volumes:
			- ./backend:/usr/src/app
			- /usr/src/app/node_modules
		restart: always
		ports:
			- "5000:5000"
		depends_on:
			- mongodb
	frontend:
		build: 
			context: ./frontend/
			dockerfile: ./Dockerfile.frontend
		volumes:
			- ./frontend:/usr/src/app 
			- /usr/src/app/node_modules
		ports:
			- "3000:3000"
		depends_on: 
			- backend